config/routes.rb
Rails.application.routes.draw do

  root :to => 'application#index'

  resources :contacts

  post 'login' => 'sessions#create'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'

  get 'register' => 'users#new'
  post 'register' => 'users#create'

  resources :courses, only: [:index, :show]
  resources :enrollments, only: [:index, :show, :create] do
    resources :lessons , only:[:index, :show]
    resources :attachments, only: [:create]
  end
  resources :attachments, only: [:show]
  resources :tests, only: [:edit, :update]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Databasedotcom::Rails::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :client, :set_contact, :redirect_if_unauthorized


  def index
  end

  private

  def redirect_if_unauthorized
    anon = %w|sessions users|.include?(params[:controller])
    logout = params[:action].eql?('destroy')
    if session[:contact]
      redirect_to root_path if anon && !logout
    else
      redirect_to login_path unless anon
    end
  end

  def client
    @client = dbdc_client
  end

  def set_contact
    @contact = session[:contact] if session[:contact]
  end
end

app/controllers/attachments_controller.rb
require 'net/http'
class AttachmentsController < ApplicationController
  include Databasedotcom::Rails::Controller

  def show
    attachment = Attachment.query("Id='#{params[:id]}'")[0]
    url = "#{attachment.client.instance_url}#{attachment.Body}"
    token = attachment.client.oauth_token

    url = URI.parse(url)
    req = Net::HTTP::Get.new(url.to_s)
    req['Authorization'] = "Bearer #{token}"
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    res = http.request(req)
    data = res.body
    send_data data, :disposition => 'attachment', :filename=>attachment.Name
  end

  def create
    @attachment = Attachment.new(attachment_params)
    if @attachment.save
      redirect_to action: :show, controller: 'enrollments', id: params[:enrollment_id]
    else
      redirect_to action: :show, controller: 'enrollments', id: params[:enrollment_id], notice: 'Something went wrong!'
    end
  end

  def attachment_params
    params.require(:attachment).permit(:ParentId).merge(Body: Base64::encode64(params[:attachment][:Body].tempfile.read), IsPrivate: false, Name: params[:attachment][:Body].original_filename)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include Databasedotcom::Rails::Controller

  def index
    @courses = Course__c.all
  end

  def show
    enrolled_query_str = "Select Id From Enrollment__c Where Course__c='#{params[:id]}' And Student__c='#{@contact['Id']}'"
    @enrolled = @client.query(enrolled_query_str).size > 0
    query_str = "Select Id, Name, Description__c, Teacher__r.Name, (Select Id, Additional_Resources__c, Name, Name__c from Classes__r) from Course__c where Id = '#{params[:id]}'"
    @course = @client.query(query_str).first
    @enrollment = Enrollment__c.new
  end


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  include Databasedotcom::Rails::Controller

  def index
    query = "Select Id, Course__r.Name, Course__r.Description__c, Course__r.Teacher__r.Name From Enrollment__c where Student__c = '#{@contact['Id']}'"
    @enrollments = @client.query(query)
    #@enrollments = Enrollment__c.find_all_by_Student__c(@contact['Id'])
  end

  def show
    enroll_query = "SELECT Id, Name, Student__c, Course__c, Course__r.Name, Course__r.Description__c, (Select Id, Score__c, Completed__c From Enrollment_Exams__r), (SELECT Id, Assignement__r.Description__c FROM Student_Assignements__r) FROM Enrollment__c WHERE Id='#{params[:id]}'"
    @enrollment = @client.query(enroll_query).first
    lessons_query = "SELECT Id, Name__c, Additional_resources__c, (Select Id, Name From Attachments) FROM Lesson__c WHERE Courses__c= '#{@enrollment.Course__c}'"
    @lessons = @client.query(lessons_query)
    @attachment = Attachment.new
  end

  def create
    enrolled_query_str = "Select Id From Enrollment__c Where Course__c='#{enrollment_params[:Course__c]}' And Student__c='#{@contact['Id']}'"
    @enrollment = @client.query(enrolled_query_str).first
    if @enrollment && @enrollment.Id
      redirect_to action: :show, id: @enrollment.Id
    else
      @enrollment = Enrollment__c.new(enrollment_params)
      if @enrollment.save
        redirect_to action: :show, id: @enrollment.Id
      else
        redirect_to action: :show, controller: 'courses', id: enrollment_params[:Course__c], notice: 'Something went wrong!'
      end
    end
  end

  #query = "Select Id, Name, Aditional_resources__c, (Select Id, Body, Name From Attachments) From Lesson__c where Id = '#{@lesson['Id']}'"

  def enrollment_params
    params.require(:enrollment__c).permit(:Course__c).merge(Student__c: @contact['Id'])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include Databasedotcom::Rails::Controller

  layout 'anon', only: [:new]

  def new
    @user = Contact.new
  end

  def create
    @contact = Contact.find_by_Email_and_Password__c(*user_params.values)
    if @contact
      session[:contact] = @contact
      redirect_to courses_url, notice: 'You are successfully logged in.'
    else
      redirect_to({ action: 'new' }, notice: 'Email or password is not correct.')
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end

  def user_params
    params.require(:contact).permit(:Email, :Password__c)
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  include Databasedotcom::Rails::Controller

  def edit
    @enrollment_exam = Enrollment_Exam__c.find(params[:id])
    @exam = Exam__c.find(@enrollment_exam.Exam__c)
    questions = "Select Id, Text__c, (Select Id, Answer__c From Question_Answers__r) From Question__c where Exam__c='#{@exam.Id}'"
    @questions = @client.query(questions)
  end

  def update
    answers = params[:StudentAnswers__r]
    @enrollment_exam = Enrollment_Exam__c.find(params[:id])
    answers.each do |k,v|
      Student_Answer__c.create(Enrollment_Exam__c: params[:id], Question__c: k, Question_Answer__c: v)
    end
    @enrollment_exam.Completed__c = true
    @enrollment_exam.Submitted_Time__c = Time.now
    @enrollment_exam.save
    redirect_to enrollment_path(@enrollment_exam.Enrollment__c)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Databasedotcom::Rails::Controller
  before_filter :load_user, :except => [:index, :new]
  layout 'anon', only: [:new]

  def index
    @users = Course__c.all
    render json: @users
  end

  def show
  end

  def new
    @user = Contact.new
  end

  def create
    p "paraaaaaa======== #{params[:Birthdate]}"
    Contact.create(contact_params)
    flash[:info] = "The user was created!"
    redirect_to root_path
  end

  def edit
  end

  def update
    @user.update_attributes User.coerce_params(params[:user])
    flash[:info] = "The user was updated!"
    redirect_to user_path(@user)
  end

  def destroy
    @user.delete
    flash[:info] = "The user was deleted!"
    redirect_to users_path
  end

  private

  def load_user
    @user = User.find(params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:FirstName, :LastName, :Email, :Phone, :Password__c, :Description, :Birthplace__c,
                                    :Salutation, :Student__c).merge(Birthdate: "#{params[:contact]['Birthdate(1i)']}-#{params[:contact]['Birthdate(2i)']}-#{params[:contact]['Birthdate(3i)']}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/courses/index.html.erb
<div class="container">
  <h3>Courses</h3>
  <hr/>
    <!-- Nav tabs -->
      <% @courses.each do |c| %>
          <div class="col-lg-4 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
              <div class="inner">
                <h2><%= c.Name %></h2>
                <p><%= c.Location__c %>&nbsp;</p>
              </div>
              <a href="<%= course_path(c.Id) %>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>

      <% end %>
</div>

app/views/courses/show.html.erb
<div class="container">
  <h3><%= @course.Name %></h3>
  <hr/>
  <div>
    <p><%= @course.Description__c %></p>
    <% if @course.Classes__r %>
        <% @course.Classes__r.each do |l| %>
            <p><%= l.Name__c %></p>
        <% end %>
    <% end %>

    <%= form_for @enrollment, url: {controller: 'enrollments', action: 'create'}, html: {class: "nifty_form"} do |f| %>
        <%= f.hidden_field :Course__c, value: @course.Id %>
        <%= submit_tag 'Enroll', disabled: @enrolled, class: 'btn bg-maroon btn-flat'%>
    <% end %>

  </div>
</div>

app/views/enrollments/index.html.erb
<div class="container">
  <h3>Enrollments</h3>
  <hr/>
  <!-- Nav tabs -->
  <% @enrollments.to_a.each do |e| %>
      <div class="col-md-6">
        <div class="box box-solid">
          <div class="box-header with-border">
            <i class="fa fa-text-width"></i>
            <h3 class="box-title"><a href="<%= enrollment_path(e.Id) %>"><%= e.Course__r.Name %></a></h3>
          </div><!-- /.box-header -->
          <div class="box-body">
            <dl class="dl-horizontal">
              <dt>Description</dt>
              <dd><%= e.Course__r.Description__c %></dd>
              <dt>Teacher</dt>
              <dd><%= p e.Course__r.Teacher__r.Name %></dd>
            </dl>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>
  <% end %>
</div>

app/views/enrollments/show.html.erb
<div class="container">
  <h2><%= @enrollment.Course__r.Name %></h2>
  <hr>

  <% @lessons.each do |lesson| %>
      <h3><%= lesson.Name__c %></h3>
      <% if lesson.respond_to?(:Attachments) && lesson.Attachments %>
          <% lesson.Attachments.each do |a| %>
              <p><%= link_to a.Name, attachment_path(a.Id) %></p>
          <% end %>
      <% end %>
      <% if lesson.Additional_Resources__c %>
          <h5>Additional Resources</h5>
          <% lesson.Additional_Resources__c.split(/[\r\n]+/).each do |resource| %>
              <p><%= link_to resource, resource %></p>
          <% end %>
      <% end %>
      <hr>
  <% end %>
  <% if @enrollment.Student_Assignements__r %>
      <h3>Assignments</h3>
      <% @enrollment.Student_Assignements__r.each do |assignment| %>
          <h4><%= assignment.Assignement__r.Description__c %></h4>
          <%= form_for @attachment, url: enrollment_attachments_path(@enrollment.Id), html: {class: 'form-inline'} do |f| %>
            <%= f.hidden_field 'ParentId', value: assignment.Id %>
            <%= f.file_field 'Body', class:'form-control', required: true  %>
            <%= f.submit 'Save', class: 'btn btn-default' %>
          <% end %>
      <% end %>
  <% end %>
  <hr>

  <% if @enrollment.Enrollment_Exams__r %>
      <h3>Exams</h3>
      <% @enrollment.Enrollment_Exams__r.each do |exam| %>
          <%= link_to 'Test', edit_test_path(exam.Id) %> <%= exam.Completed__c ? " - Completed (#{exam.Score__c})" : ''%>
      <% end %>
  <% end %>

</div>

app/views/layouts/anon.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearningForce</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition register-page">
<%= yield %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearningForce</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="fixed sidebar-mini skin-blue">
  <header class="main-header">
    <a href="/" class="logo">
      <span class="logo-mini"><b>L</b>F</span>
      <span class="logo-lg"><b>Learning</b>Force</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs"><%= "#{@contact['FirstName']} #{@contact['LastName']}" %></span>
            </a>
            <ul class="dropdown-menu">
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <%= link_to 'Logout', logout_path, :method => :delete%>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <!-- Inner sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">

        <li class="active">
          <a href="/courses">
            <i class="fa fa-th"></i> <span>Courses</span>
          </a>
        </li>
        <li class="active">
          <a href="/enrollments">
            <i class="fa fa-tasks"></i> <span>Enrollments</span>
          </a>
        </li>

      </ul><!-- /.sidebar-menu -->

    </div><!-- /.sidebar -->
  </aside><!-- /.main-sidebar -->


  <div class="content-wrapper">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/new.html.erb
<body class="hold-transition register-page">
  <div class="register-box">
    <div class="register-logo">
      <a href="/"><b>Learning</b>Force</a>
    </div>
    <div class="register-box-body">
      <p class="login-box-msg">Register a new membership</p>
      <%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
          <%= f.hidden_field :Student__c, value: true %>
          <div class="form-group has-feedback">
            <%= f.select :Salutation, {Mr: 'Mr', Mrs: 'Mrs'}, {}, class: 'form-control', placeholder: 'Salutation', required: true %>
          </div>
          <div class="form-group has-feedback">
            <%= f.text_field :FirstName, class: 'form-control', placeholder: 'First Name', required: true %>
            <i class="fa fa-user form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.text_field :LastName, class: 'form-control', placeholder: 'Last name', required: true %>
            <i class="fa fa-user form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.text_field :Birthplace__c, class: 'form-control', placeholder: 'Place of Birth', required: true %>
            <i class="fa fa-user form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.label :Birthday %>
            <%= f.date_select :Birthdate, class: 'form-control', placeholder: 'Birthday', required: true, start_year: 1960 %>
          </div>
          <div class="form-group has-feedback">
            <%= f.email_field :Email, class: 'form-control', placeholder: 'Email', required: true %>
            <i class="fa fa-envelope form-control-feedback"></i>
          </div>
          <div class="form-group has-feedback">
            <%= f.password_field :Password__c, class: 'form-control', placeholder: 'Password', required: true %>
            <i class="fa fa-lock form-control-feedback"></i>
          </div>
          <div class="form-group">
            <%= f.submit 'Create', class: 'btn btn-primary btn-block btn-flat' %>
          </div>
      <% end %>
      <a href="/login" class="text-center">I already have a membership</a>
    </div>
  </div>
</body>